-- MySQL Script generated by MySQL Workbench
-- Wed Sep  6 16:33:10 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_certificado_iestp
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_certificado_iestp` ;

-- -----------------------------------------------------
-- Schema bd_certificado_iestp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_certificado_iestp` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `bd_certificado_iestp` ;

-- -----------------------------------------------------
-- Table `cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cargo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cargo` (
  `idcargo` INT NOT NULL AUTO_INCREMENT,
  `nombre_cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcargo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categoria` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliente` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `dni` INT(8) NOT NULL,
  `nombre_cliente` VARCHAR(100) NOT NULL,
  `apellido_paterno` VARCHAR(100) NOT NULL,
  `apellido_materno0` VARCHAR(100) NOT NULL,
  `celular_cliente` INT(9) NOT NULL,
  `correo_cliente` TEXT NULL,
  `idgenero` INT NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `curso` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `codigo` CHAR NOT NULL,
  `nombre_curso` VARCHAR(100) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `diseño` TEXT NULL,
  `idinstructor` INT NOT NULL,
  `idcategoria` INT NOT NULL,
  `identidad` INT NOT NULL,
  `idespecialista` INT NOT NULL,
  `idhora_lectiva` INT NOT NULL,
  PRIMARY KEY (`idcurso`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `empleado` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `empleado` (
  `idempleado` INT NOT NULL AUTO_INCREMENT,
  `nombre_empleado` VARCHAR(80) NOT NULL,
  `apellidos_empleado` VARCHAR(80) NOT NULL,
  `celular_empleado` INT(9) NOT NULL,
  `correo_empleado` TEXT NOT NULL,
  `idcargo` INT NOT NULL,
  PRIMARY KEY (`idempleado`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `entidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entidad` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `entidad` (
  `identidad` INT NOT NULL AUTO_INCREMENT,
  `ruc` INT NOT NULL,
  `nombre_entidad` VARCHAR(100) NOT NULL,
  `celular_entidad` INT(9) NOT NULL,
  `direccion_entidad` TEXT NULL,
  `descripcion_entidad` TEXT NULL,
  PRIMARY KEY (`identidad`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `especialista`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `especialista` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `especialista` (
  `idespecialista` INT NOT NULL AUTO_INCREMENT,
  `nombres_especialista` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `firma_especialista` TEXT NOT NULL,
  `idcargo` INT NOT NULL,
  PRIMARY KEY (`idespecialista`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `genero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `genero` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `genero` (
  `idgenero` INT NOT NULL AUTO_INCREMENT,
  `nombre_genero` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idgenero`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `hora_lectiva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hora_lectiva` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `hora_lectiva` (
  `idhora_lectiva` INT NOT NULL AUTO_INCREMENT,
  `horas` INT(3) NOT NULL,
  PRIMARY KEY (`idhora_lectiva`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `inscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inscripcion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `inscripcion` (
  `idinscripcion` INT NOT NULL,
  `fecha_inscripcion` VARCHAR(45) NULL,
  `idcurso` INT NOT NULL,
  `idcliente` INT NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idinscripcion`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `instructor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `instructor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `instructor` (
  `idinstructor` INT NOT NULL AUTO_INCREMENT,
  `nombre_instructor` VARCHAR(100) NOT NULL,
  `apellido_instructor` VARCHAR(100) NOT NULL,
  `grado_instruccion` VARCHAR(100) NOT NULL,
  `celular_instruccion` INT(9) NOT NULL,
  `correo_instruccion` TEXT NULL,
  `firma_digital` TEXT NOT NULL,
  `idgenero` INT NOT NULL,
  PRIMARY KEY (`idinstructor`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `modulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modulo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `modulo` (
  `idmodulo` INT NOT NULL AUTO_INCREMENT,
  `nombre_modulo` TEXT NOT NULL,
  PRIMARY KEY (`idmodulo`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `modulo_rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `modulo_rol` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `modulo_rol` (
  `idmodulo_rol` INT NOT NULL,
  `idmodulo` INT NOT NULL,
  `idrol` INT NOT NULL,
  PRIMARY KEY (`idmodulo_rol`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rol` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `rol` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NOT NULL,
  `clave` VARCHAR(10) NOT NULL,
  `estado` TINYINT NOT NULL,
  `idempleado` INT NOT NULL,
  `idrol` INT NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
